#!/usr/bin/env python3
"""Sim2sim: Stand the biped at default joint positions in MuJoCo.

Usage:
    python sim2sim/stand_mujoco.py [--headless] [--duration 10]

PD control in Python, torques sent to MuJoCo motor actuators.
MJCF generated by urdf2mjcf (K-Scale) from light URDF.
"""

import argparse
import os
import time

import numpy as np
import mujoco

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MJCF_PATH = os.path.join(REPO_ROOT, "mjcf", "sim2sim", "robot.mjcf")

# ─── Physics ───────────────────────────────────────────────────────────────────
PHYSICS_DT = 0.0005       # MuJoCo timestep (2000 Hz, matches Berkeley Lite)
POLICY_DT = 0.02           # PD loop (50 Hz)
SUBSTEPS = int(round(POLICY_DT / PHYSICS_DT))  # = 40

# ─── Joint ordering (matches actuator order in robot.mjcf) ────────────────────
JOINT_NAMES = [
    "right_hip_pitch_04", "right_hip_roll_03", "right_hip_yaw_03",
    "right_knee_04", "right_foot_pitch_02", "right_foot_roll_02",
    "left_hip_pitch_04", "left_hip_roll_03", "left_hip_yaw_03",
    "left_knee_04", "left_foot_pitch_02", "left_foot_roll_02",
]

# ─── Default standing pose ────────────────────────────────────────────────────
DEFAULT_JOINT_POS = np.array([
    -0.08,  0.0,  0.0,  0.25, -0.17,  0.0,   # right leg
     0.08,  0.0,  0.0,  0.25, -0.17,  0.0,   # left leg
], dtype=np.float32)

# ─── PD gains (tuned for stable standing) ─────────────────────────────────────
#   hip_pitch: Kp=10, Kd=2 (LOW — higher oscillates!)
#   hip_roll/yaw: Kp=30, Kd=3
#   knee: Kp=40, Kd=3
#   ankle_pitch: Kp=80, Kd=3.2 (HIGH — main load bearing)
#   ankle_roll: Kp=14, Kd=0.8
JOINT_KP = np.array([
    10.0, 30.0, 30.0, 40.0, 80.0, 14.0,
    10.0, 30.0, 30.0, 40.0, 80.0, 14.0,
], dtype=np.float32)

JOINT_KD = np.array([
    2.0, 3.0, 3.0, 3.0, 3.2, 0.8,
    2.0, 3.0, 3.0, 3.0, 3.2, 0.8,
], dtype=np.float32)

EFFORT_LIMITS = np.array([
    40.0, 40.0, 40.0, 60.0, 30.0, 30.0,
    40.0, 40.0, 40.0, 60.0, 30.0, 30.0,
], dtype=np.float32)

BASE_HEIGHT = 0.802


def main():
    parser = argparse.ArgumentParser(description="Biped standing in MuJoCo")
    parser.add_argument("--headless", action="store_true")
    parser.add_argument("--duration", type=float, default=10.0)
    args = parser.parse_args()

    model = mujoco.MjModel.from_xml_path(MJCF_PATH)
    data = mujoco.MjData(model)
    model.opt.timestep = PHYSICS_DT
    assert model.nu == 12

    qp_idx = np.array([
        model.jnt_qposadr[mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, n)]
        for n in JOINT_NAMES
    ])
    qv_idx = np.array([
        model.jnt_dofadr[mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, n)]
        for n in JOINT_NAMES
    ])

    mujoco.mj_resetData(model, data)
    data.qpos[2] = BASE_HEIGHT
    data.qpos[qp_idx] = DEFAULT_JOINT_POS
    data.qvel[:] = 0.0
    mujoco.mj_forward(model, data)

    total_mass = sum(model.body_mass[i] for i in range(model.nbody))
    print(f"MJCF: {MJCF_PATH}")
    print(f"Mass: {total_mass:.1f}kg, Spawn z: {BASE_HEIGHT}")
    print(f"Physics: {1/PHYSICS_DT:.0f}Hz, PD: {1/POLICY_DT:.0f}Hz")

    if not args.headless:
        viewer = mujoco.viewer.launch_passive(model, data)
    else:
        viewer = None

    n_steps = int(args.duration / POLICY_DT)
    try:
        for step in range(n_steps):
            t0 = time.perf_counter()
            jp = data.qpos[qp_idx]
            jv = data.qvel[qv_idx]
            torques = JOINT_KP * (DEFAULT_JOINT_POS - jp) + JOINT_KD * (0.0 - jv)
            torques = np.clip(torques, -EFFORT_LIMITS, EFFORT_LIMITS)

            for _ in range(SUBSTEPS):
                data.ctrl[:] = torques
                mujoco.mj_step(model, data)

            if viewer is not None:
                viewer.sync()
                if not viewer.is_running():
                    break

            dt = time.perf_counter() - t0
            if POLICY_DT - dt > 0:
                time.sleep(POLICY_DT - dt)

            if step % 50 == 0:
                print(f"[{step * POLICY_DT:.1f}s] z={data.qpos[2]:.3f} qw={data.qpos[3]:.3f} con={data.ncon}")

    except KeyboardInterrupt:
        print("\nStopped.")
    finally:
        if viewer is not None:
            viewer.close()


if __name__ == "__main__":
    main()
