R_hip_pitch:
  motor_min: 2.6746
  motor_max: 5.9628
  offset: 4.8911
  direction: 1
R_hip_roll:
  motor_min: 2.994
  motor_max: 5.4703
  offset: 5.263
  direction: 1
R_hip_yaw:
  motor_min: 0.6466
  motor_max: 3.7971
  offset: 2.2174
  direction: 1
R_knee:
  motor_min: 1.6782
  motor_max: 4.2914
  offset: 1.6782
  direction: -1
R_foot_top:
  motor_min: 3.6518
  motor_max: 5.9121
  offset: 4.5746
  direction: -1
R_foot_bottom:
  motor_min: 5.1516
  motor_max: 7.3676
  offset: 6.5198
  direction: -1
L_hip_pitch:
  motor_min: 1.5567
  motor_max: 4.823
  offset: 2.6039
  direction: 1
L_hip_roll:
  motor_min: 1.7933
  motor_max: 4.2117
  offset: 2.0027
  direction: 1
L_hip_yaw:
  motor_min: 1.289
  motor_max: 4.4345
  offset: 2.8598
  direction: 1
L_knee:
  motor_min: 5.0297
  motor_max: 7.6306
  offset: 5.0297
  direction: 1
L_foot_top:
  motor_min: 4.2182
  motor_max: 6.4732
  offset: 5.5863
  direction: -1
L_foot_bottom:
  motor_min: 4.0744
  motor_max: 6.3382
  offset: 4.9972
  direction: -1
