R_hip_pitch:
  motor_min: -0.6378
  motor_max: 2.6339
  offset: 1.5788
  direction: 1
R_hip_roll:
  motor_min: 3.1206
  motor_max: 5.6126
  offset: 5.3895
  direction: 1
R_hip_yaw:
  motor_min: 1.1313
  motor_max: 4.2857
  offset: 2.7021
  direction: 1
R_knee:
  motor_min: -1.8707
  motor_max: 0.7455
  offset: 0.7455
  direction: -1
R_foot_top:
  motor_min: 1.6207
  motor_max: 3.9087
  offset: 2.5435
  direction: -1
R_foot_bottom:
  motor_min: -0.2174
  motor_max: 2.0149
  offset: 1.1507
  direction: -1
L_hip_pitch:
  motor_min: -0.8606
  motor_max: 2.4264
  offset: 0.1866
  direction: 1
L_hip_roll:
  motor_min: 4.9388
  motor_max: 7.432
  offset: 5.1482
  direction: 1
L_hip_yaw:
  motor_min: 2.9948
  motor_max: 6.1561
  offset: 4.5656
  direction: 1
L_knee:
  motor_min: 0.2708
  motor_max: 2.8675
  offset: 0.2708
  direction: 1
L_foot_top:
  motor_min: -0.6654
  motor_max: 1.3753
  offset: 0.7028
  direction: -1
L_foot_bottom:
  motor_min: 1.0228
  motor_max: 3.2809
  offset: 1.9457
  direction: -1
