chirp:
  joints:
    L_hip_pitch:
      freq: 0.5
      max: 28.32
      min: -18.44
    R_hip_pitch:
      freq: 0.5
      max: 18.44
      min: -28.32
    L_hip_roll:
      freq: 0.5
      max: 32.50
      min: -3.00
    R_hip_roll:
      freq: 0.5
      max: 3.00
      min: -32.50
    L_hip_yaw:
      freq: 0.5
      max: 22.50
      min: -22.50
    R_hip_yaw:
      freq: 0.5
      max: 22.50
      min: -22.50
    L_knee:
      freq: 0.5
      max: 49.49
      min: 10.75
    R_knee:
      freq: 0.5
      max: 49.49
      min: 10.75
    L_foot_pitch:
      freq: 0.5
      max: 18.09
      min: -37.94
    R_foot_pitch:
      freq: 0.5
      max: 18.09
      min: -37.94
    L_foot_roll:
      freq: 0.5
      max: 10.51
      min: -10.51
    R_foot_roll:
      freq: 0.5
      max: 10.51
      min: -10.51
