control_params:
  joints:
    L_foot_pitch:
      default_pos: -0.17
      kd: 2.8
      kp: 30.0
      limit_max: 0.524
      limit_min: -0.873
    L_foot_roll:
      default_pos: 0.1
      kd: 2.8
      kp: 30.0
      limit_max: 0.262
      limit_min: -0.262
    L_hip_pitch:
      default_pos: -0.08
      kd: 20.0
      kp: 180.0
      limit_max: 2.217
      limit_min: -1.047
    L_hip_roll:
      default_pos: 0.1
      kd: 15.0
      kp: 180.0
      limit_max: 2.269
      limit_min: -0.209
    L_hip_yaw:
      default_pos: 0.0
      kd: 15.0
      kp: 180.0
      limit_max: 1.571
      limit_min: -1.571
    L_knee:
      default_pos: 0.25
      kd: 10.0
      kp: 180.0
      limit_max: 2.705
      limit_min: 0.0
    R_foot_pitch:
      default_pos: -0.17
      kd: 2.8
      kp: 30.0
      limit_max: 0.524
      limit_min: -0.873
    R_foot_roll:
      default_pos: -0.1
      kd: 2.8
      kp: 30.0
      limit_max: 0.262
      limit_min: -0.262
    R_hip_pitch:
      default_pos: 0.08
      kd: 20.0
      kp: 180.0
      limit_max: 1.047
      limit_min: -2.217
    R_hip_roll:
      default_pos: -0.1
      kd: 15.0
      kp: 180.0
      limit_max: 0.209
      limit_min: -2.269
    R_hip_yaw:
      default_pos: 0.0
      kd: 15.0
      kp: 180.0
      limit_max: 1.571
      limit_min: -1.571
    R_knee:
      default_pos: 0.25
      kd: 10.0
      kp: 180.0
      limit_max: 2.705
      limit_min: 0.0
