# Step response test configuration
# step_min: target position in DEGREES
# step_max: target position in DEGREES
# period: total duration of one full cycle in seconds

step:
  joints:
    R_hip_pitch:
      step_max: 20
      step_min: -20
      period: 2.0
    R_hip_roll:
      step_max: 20
      step_min: -10
      period: 2.0
    R_hip_yaw:
      step_max: 20
      step_min: -20
      period: 2.0
    R_knee:
      step_max: 40
      step_min: 15
      period: 2.0
    R_foot_pitch:
      step_max: 15
      step_min: -15
      period: 2.0
    R_foot_roll:
      step_max: 15
      step_min: -15
      period: 2.0
    L_hip_pitch:
      step_max: 20
      step_min: -20
      period: 2.0
    L_hip_roll:
      step_max: 20
      step_min: -10
      period: 2.0
    L_hip_yaw:
      step_max: 20
      step_min: -20
      period: 2.0
    L_knee:
      step_max: 40
      step_min: 15
      period: 2.0
    L_foot_pitch:
      step_max: 15
      step_min: -15
      period: 2.0
    L_foot_roll:
      step_max: 15
      step_min: -15
      period: 2.0
