# Wiggle test configuration
# pos/neg: amplitude range above/below default position (in DEGREES)
# frequency: sine wave frequency (Hz)

wiggle:
  joints:
    R_hip_pitch:
      pos: 28.6
      neg: -28.6
      freq: 0.5
    R_hip_roll:
      pos: 11.5
      neg: -22.9
      freq: 0.5
    R_hip_yaw:
      pos: 11.5
      neg: -11.5
      freq: 0.5
    R_knee:
      pos: 40
      neg: -10
      freq: 0.5
    R_foot_pitch:
      pos: 28.6
      neg: -28.6
      freq: 0.5
    R_foot_roll:
      pos: 17.2
      neg: -17.2
      freq: 0.5
    L_hip_pitch:
      pos: 11.5
      neg: -11.5
      freq: 0.5
    L_hip_roll:
      pos: 22.9
      neg: -11.5
      freq: 0.5
    L_hip_yaw:
      pos: 28.6
      neg: -28.6
      freq: 0.5
    L_knee:
      pos: 40
      neg: -10
      freq: 0.5
    L_foot_pitch:
      pos: 17.2
      neg: -17.2
      freq: 0.5
    L_foot_roll:
      pos: 11.5
      neg: -11.5
      freq: 0.5
