# Wiggle test configuration
# max/min: absolute joint angles (in DEGREES, relative to URDF 0)
# frequency: sine wave frequency (Hz)

wiggle:
  joints:
    R_hip_pitch:
      freq: 0.5
      max: 20.0
      min: -20.0
    R_hip_roll:
      freq: 0.5
      max: 15
      min: -10
    R_hip_yaw:
      freq: 0.5
      max: 15.0
      min: -15.0
    R_knee:
      freq: 0.5
      max: 40.0
      min: 10.0
    R_foot_pitch:
      freq: 0.5
      max: 15.0
      min: -15.0
    R_foot_roll:
      freq: 0.5
      max: 10.0
      min: -10.0
    L_hip_pitch:
      freq: 0.5
      max: 20.0
      min: -20.0
    L_hip_roll:
      freq: 0.5
      max: 15
      min: -10
    L_hip_yaw:
      freq: 0.5
      max: 15.0
      min: -15.0
    L_knee:
      freq: 0.5
      max: 40.0
      min: 10.0
    L_foot_pitch:
      freq: 0.5
      max: 15.0
      min: -15.0
    L_foot_roll:
      freq: 0.5
      max: 10.0
      min: -10.0
