R_hip_pitch:
  motor_min: -0.6393
  motor_max: 2.632
  offset: 1.5773
  limit_lo: -2.2166
  limit_hi: 1.0472
  urdf_lower: -2.2166
  urdf_upper: 1.0472
  default_pos: 0.2
R_hip_roll:
  motor_min: -2.1143
  motor_max: 0.3774
  offset: 0.1547
  limit_lo: -2.2689
  limit_hi: 0.2094
  urdf_lower: -2.2689
  urdf_upper: 0.2094
  default_pos: 0.0
R_hip_yaw:
  motor_min: 2.4299
  motor_max: 5.5831
  offset: 4.0007
  limit_lo: -1.5708
  limit_hi: 1.5708
  urdf_lower: -1.5708
  urdf_upper: 1.5708
  default_pos: 0.0
R_knee:
  motor_min: 1.4243
  motor_max: 4.2013
  offset: 1.4243
  limit_lo: 0.0
  limit_hi: 2.7053
  urdf_lower: 0.0
  urdf_upper: 2.7053
  default_pos: 0.4
R_foot_pitch:
  motor_min: 3.7311
  motor_max: 6.0326
  offset: 3.7311
  limit_lo: 3.7311
  limit_hi: 6.0326
  urdf_lower: -0.8727
  urdf_upper: 0.5236
  default_pos: -0.2
R_foot_roll:
  motor_min: 3.898
  motor_max: 6.2143
  offset: 3.898
  limit_lo: 3.898
  limit_hi: 6.2143
  urdf_lower: -0.2618
  urdf_upper: 0.2618
  default_pos: 0.0
L_hip_pitch:
  motor_min: -0.8614
  motor_max: 1.7726
  offset: 0.1858
  limit_lo: -1.0472
  limit_hi: 2.2166
  urdf_lower: -1.0472
  urdf_upper: 2.2166
  default_pos: -0.2
L_hip_roll:
  motor_min: 4.9396
  motor_max: 7.4281
  offset: 5.149
  limit_lo: -0.2094
  limit_hi: 2.2689
  urdf_lower: -0.2094
  urdf_upper: 2.2689
  default_pos: 0.0
L_hip_yaw:
  motor_min: 3.0044
  motor_max: 6.1653
  offset: 4.5752
  limit_lo: -1.5708
  limit_hi: 1.5708
  urdf_lower: -1.5708
  urdf_upper: 1.5708
  default_pos: 0.0
L_knee:
  motor_min: 0.2727
  motor_max: 2.8874
  offset: 0.2727
  limit_lo: 0.0
  limit_hi: 2.7053
  urdf_lower: 0.0
  urdf_upper: 2.7053
  default_pos: 0.4
L_foot_pitch:
  motor_min: -0.7624
  motor_max: 1.5083
  offset: -0.7624
  limit_lo: -0.7624
  limit_hi: 1.5083
  urdf_lower: -0.8727
  urdf_upper: 0.5236
  default_pos: -0.2
L_foot_roll:
  motor_min: 1.0044
  motor_max: 3.2744
  offset: 1.0044
  limit_lo: 1.0044
  limit_hi: 3.2744
  urdf_lower: -0.2618
  urdf_upper: 0.2618
  default_pos: 0.0
